name: "aloi_sim"
class_definition:
  _target_: maml.data.ALOISim
  root: "."
max_epochs: 20
lr_min: 1e-4
lr_max: 1e-1
min_samples: 10
alpha_1: 0.0
beta_1: 1.0
alpha_2: 0.5
beta_2: 2.0
num_workers: 4
batch_size: 50
optimizer:
  class_definition: torch.optim.RAdam
  params:
    weight_decay: 0
    lr: 1e-2


