name: "flowers_102_sim"
class_definition:
  _target_: maml.data.Flowers102Sim
  root: "."
max_epochs: 5
min_samples: 10
lr_min: 1e-4
lr_max: 1e-1
alpha_1: 0.0
beta_1: 1.5
alpha_2: 1.0
beta_2: 2.0
num_workers: 4
batch_size: 64
optimizer:
  class_definition: torch.optim.RAdam
  params:
    lr: 1e-2
    weight_decay: 1e-4