name: "svhn_sim"
class_definition:
  _target_: maml.data.SVHNSim
  root: "."
  download: True
max_epochs: 10
min_samples: 10
alpha_1: 0.0
beta_1: 0.5
alpha_2: 0.5
beta_2: 2.0
num_workers: 4
batch_size: 128
optimizer:
  class_definition: torch.optim.RAdam
  params:
    lr: 1e-3
    weight_decay: 1e-4