name: "geo_reg_f"
class_definition:
  _target_: maml.classifiers.RegCrowdNetClassifier
params:
  regularization: "geo-reg-f"
  lmbda: 1e-3
annotators: "index"
aggregation_method: null
embed_size: null
